apiVersion: v1
kind: Service
metadata:
  name: djangoblog-sitemap-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30004
  selector:
    app: djangoblog-sitemap-app

