apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoblog-rss-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djangoblog-rss-app
  template:
    metadata:
      labels:
        app: djangoblog-rss-app
    spec:
      containers:
      - name: djangoblog-main-app
        image: regiapriandi012/django-rss-arm64:latest
        readinessProbe:
          httpGet:
            path: /feed/rss
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /feed/rss
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_USER
          value: "regiapriandi"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: DATABASE_NAME
          value: "postgres"
