apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoblog-main-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djangoblog-main-app
  template:
    metadata:
      labels:
        app: djangoblog-main-app
    spec:
      containers:
      - name: djangoblog-main-app
        image: regiapriandi012/django-main-arm64:latest
        readinessProbe:
          httpGet:
            path: /blog
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /blog
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_USER
          value: "regiapriandi"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: DATABASE_NAME
          value: "postgres"
        volumeMounts:
        - name: djangoblog-admin-media
          mountPath: /code/media
      restartPolicy: Always
      volumes:
      - name: djangoblog-admin-media
        persistentVolumeClaim:
          claimName: djangoblog-admin-media-pvc
