apiVersion: v1
kind: Service
metadata:
  name: djangoblog-main-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30002
  selector:
    app: djangoblog-main-app
