apiVersion: batch/v1
kind: Job
metadata:
  name: djangoblog-admin-app-migrate
spec:
  template:
    spec:
      containers:
        - name: djangoblog-admin-app
          image: regiapriandi012/django-admin-arm64:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py makemigrations djangoBlogApp && python manage.py migrate"]
          env:
            - name: DATABASE_USER
              value: "regiapriandi"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "postgres"
      restartPolicy: Never
  backoffLimit: 0

