apiVersion: batch/v1
kind: Job
metadata:
  name: djangoblog-admin-app-adddomain
spec:
  template:
    spec:
      containers:
        - name: djangoblog-admin-app
          image: regiapriandi012/django-rss-arm64:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py shell -c \"from django.contrib.sites.models import Site; Site.objects.filter(domain='example.com').update(name='Regiapriandi Blog', domain='regiapriandi.com')\""]
          env:
            - name: DATABASE_USER
              value: "regiapriandi"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "postgres"
      restartPolicy: Never
  backoffLimit: 0

