apiVersion: v1
kind: Service
metadata:
  name: djangoblog-admin-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: djangoblog-admin-app
