apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: djangoblog-admin-media-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoblog-admin-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djangoblog-admin-app
  template:
    metadata:
      labels:
        app: djangoblog-admin-app
    spec:
      containers:
      - name: djangoblog-admin-app
        image: regiapriandi012/django-admin-arm64:latest
        readinessProbe:
          httpGet:
            path: /admin
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /admin
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_USER
          value: "regiapriandi"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: DATABASE_NAME
          value: "postgres"
        volumeMounts:
        - name: djangoblog-admin-media
          mountPath: /code/media
      restartPolicy: Always
      volumes:
      - name: djangoblog-admin-media
        persistentVolumeClaim:
          claimName: djangoblog-admin-media-pvc
